import type { Metadata } from "next";
import "./globals.css";
import ClientBoot from "@/components/ClientBoot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased bg-[var(--background)] text-[var(--foreground)]`}>
        <ClientBoot />
        {children}
      </body>
    </html>
  );
}
