name: Deploy to S3 + CloudFront

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  # Set default region; override by adding repo/org secret AWS_REGION
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Next static export)
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2


      - name: Sync to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME || vars.S3_BUCKET_NAME || env.S3_BUCKET }}
        run: |
          if [ -z "${S3_BUCKET:-}" ]; then echo "S3 bucket not configured. Set secret S3_BUCKET_NAME or repo var S3_BUCKET_NAME"; exit 1; fi
          if [ ! -d "out" ]; then echo "out/ not found. Did Next build run with output: 'export'?"; exit 1; fi
          aws s3 sync ./out s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront cache
        if: env.DISTRIBUTION_ID != ''
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID || vars.CLOUDFRONT_DISTRIBUTION_ID || env.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"
